name: interact
description: A collection of customizable interactive command-line components.
version: 3.0.0
repository: https://github.com/frencojobs/interact

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_console: ^4.1.2
  meta: ^1.8.0

dev_dependencies:
  coverage: ^1.15.0
  fake_async: ^1.3.1
  lint: ^2.0.1
  test: ^1.22.2
